version: 2.1

orbs:
  node: 'circleci/node:x.y'

jobs:
  test:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run integration and unit tests

workflows:
  integration_unit_test:
    jobs:
      - test