version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/node:12
        environment:
          DATABASE_URL: postgresql://postgres@localhost/dev
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: dev
    steps:
      - checkout
      - run: sudo apt-get install postgresql-client-9.6
      # - run: sudo service postgresql start
      # - run: export DATABASE_URL=postgres://ubuntu@localhost:5432/dev
      - run: psql -d $DATABASE_URL -d dev -a -f setup/CreateDB.sql
      - run: yarn install
      - run: yarn test

# Orchestrate our job run sequence
workflows:
  ci_test:
    jobs:
      - test