version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/node:12
      - image: postgres:9.5
        env:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=dev
    steps:
      - checkout
      - run: sudo apt-get install postgresql-client-9.6
      - run: export DATABASE_URL=postgres://ubuntu@localhost:5432/dev
      - run: psql -d $DATABASE_URL -d circle_test -a -f setup/CreateDB.sql
      - run: yarn install
      - run: yarn test

# Orchestrate our job run sequence
workflows:
  ci_test:
    jobs:
      - test