version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dev
    steps:
      - checkout
      - run: sudo apt-get install postgresql-client
      - run: ./migrate.sh
      - run: yarn install
      - run: yarn test

workflows:
  ci_test:
    jobs:
      - run_tests