export default {
  NORTH: 'NORTH',
  SOUTH: 'SOUTH',
  WEST: 'WEST',
  EAST: 'EAST',
  CENTRAL: 'CENTRAL',
  NORTHEAST: 'NORTH-EAST',
  NORTHWEST: 'NORTH-WEST',
  SOUTHEAST: 'SOUTH-EAST',
  SOUTHWEST: 'SOUTH-WEST',
};
