export const PET_DELIVERY_MODE = {
  PET_OWNER_DELIVER: 'PET_OWNER_DELIVER',
  CARE_TAKER_PICK_UP: 'CARE_TAKER_PICK_UP',
  TRANSFER_THROUGH_PCS: 'TRANSFER_THROUGH_PCS',
};

export const BID_PAYMENT_MODE = {
  CASH: 'CASH',
  CREDIT: 'CREDIT',
};

export const TIME_FORMAT = 'DD-MM-YYYY HH24:MI:SS';
