export default {
  PET_OWNER: 'PET_OWNER',
  ADMINISTRATOR: 'ADMINISTRATOR',
  CARE_TAKER: 'CARE_TAKER',
  CARE_TAKER_FULL_TIMER: 'CARE_TAKER_FULL_TIMER',
  CARE_TAKER_PART_TIMER: 'CARE_TAKER_PART_TIMER',
};
